apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
spec:
  clusterIP: None                 # Headless (StatefulSet DNS)
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
