apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30306   # Minikube 기본 NodePort 대역(30000-32767) 내에서 선택
  selector:
    app: mysql
