apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-hba
data:
  pg_hba.conf: |
    # 비밀번호 인증 강제 (TCP)
    # 필요 시 0.0.0.0/0 대신 내부 대역으로 좁히세요.
    local   all             all                                     scram-sha-256
    host    all             all             127.0.0.1/32            scram-sha-256
    host    all             all             ::1/128                 scram-sha-256
    host    all             all             0.0.0.0/0               scram-sha-256
