apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgresql
spec:
  type: NodePort
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      nodePort: 30432   # Minikube NodePort 대역(30000-32767) 내 임의 선택
  selector:
    app: postgresql
