apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: postgresql
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgresql
          image: postgres:16
          imagePullPolicy: IfNotPresent
          # ↓↓↓ 'hba_file' 지정은 제거. 기본 경로(PGDATA/pg_hba.conf)를 사용.
          args:
            - "-c"
            - "password_encryption=scram-sha-256"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_USER
            # 선택: 신규 init 시 기본 인증을 scram으로
            - name: POSTGRES_INITDB_ARGS
              value: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
            # ↓↓↓ ConfigMap 단일 파일을 PGDATA/pg_hba.conf에 오버레이
            - name: hba
              mountPath: /var/lib/postgresql/data/pg_hba.conf
              subPath: pg_hba.conf
          readinessProbe:
            exec:
              command: ["bash","-lc","pg_isready -h 127.0.0.1 -p 5432 -U $POSTGRES_USER"]
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["bash","-lc","pg_isready -h 127.0.0.1 -p 5432 -U $POSTGRES_USER"]
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "1Gi" }
      volumes:
        - name: init-sql
          configMap:
            name: postgresql-init-sql
        # ↓↓↓ HBA ConfigMap(단일 파일)을 subPath로 사용
        - name: hba
          configMap:
            name: postgresql-hba
            items:
              - key: pg_hba.conf
                path: pg_hba.conf
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
